### ISSUE TITLE
BadConnection("Unable to open the database file")' when changing database link

### ISSUE THREAD

**Issue by ghost** [emmanueltouzery/projectpad2#2]
I'm using the flatpak version. I linked the database file with

`ln -s /home/user/projectpad/projectpad.db /home/user/.var/app/com.github.emmanueltouzery.projectpad/data/projectpad/projectpad.db`

And it works the database is saved. But if I want to change the database file location:

`$ rm /home/user/.var/app/com.github.emmanueltouzery.projectpad/data/projectpad/projectpad.db`
`$ ln -s /home/user/new_location/projectpad/projectpad.db /home/user/.var/app/com.github.emmanueltouzery.projectpad/data/projectpad/projectpad.db`

`projectpad.db` is the same database file as before only on a new location.

Then when I try starting projectpad again I receive the error and projectpad closes itself:

`$ flatpak run com.github.emmanueltouzery.projectpad
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BadConnection("Unable to open the database file")', projectpad/src/sql_thread.rs:35:92
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

How can I change the projectpad database location?

**Comment by emmanueltouzery** [comment]
Hi! yes i think it's what I mention in the readme, I believe it's flatpak which prevents the application from accessing  the disk in locations it's not supposed to. The flatpak is in fact limited such that it cannot access your disk except in its own data folder and through file open/save dialogs, for security.

I mention this at the very bottom of the README:

> if you use flatpak, you must grant the application access to the folder where the DB is stored, through a command like `flatpak override com.github.emmanueltouzery.projectpad --filesystem=~/Dropbox/projectpad/ --user`.

So in your case that would be  `flatpak override com.github.emmanueltouzery.projectpad --filesystem=/home/user/new_location/projectpad/ --user`.

Can you try that and let me know whether that works?

**Comment by ghost** [comment]
It worked! I forgot to execute that command. thanks. closing
